version: '3.4'

services:

  # Telegram bot
  masterchef-bot:
    restart: always
    build:
      context: ./bot
      dockerfile: ./Dev.Dockerfile

    env_file:
      - ./.env
      
    volumes:
      - ./bot/:/go/masterchef-bot

    depends_on:
      - mongo

  # Mongo
  mongo:
    container_name: mongo
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: master
      MONGO_INITDB_ROOT_PASSWORD: chef
      MONGO_INITDB_DATABASE: "${DATABASE_NAME}"
    ports: 
      - '27018:27017'
    volumes:
      - mongostore:/data/db
      - ./mongo_db:/docker-entrypoint-initdb.d

  # Web UI for mongo db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: master
      ME_CONFIG_MONGODB_ADMINPASSWORD: chef


volumes:
  mongostore:
