version: '3.4'

services:

  masterchef-bot:
    restart: always

    environment:
      BOT_API_KEY: "${BOT_API_KEY}"
      DEBUG_MODE: "${DEBUG_MODE}"
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_CONNECTION: "${DATABASE_CONNECTION}"

