version: '3.4'

services:

  masterchef-bot:
    restart: always
    build:
      context: .
      dockerfile: ./Dev.Dockerfile

    environment:
      API_KEY: "${API_KEY}"
      DEBUG_MODE: "true"
      
    volumes:
      - ./:/go/masterchef-bot

    depends_on:
      - mongo

  # Mongo
  mongo:
    container_name: mongo
    image: mongo:3.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: master
      MONGO_INITDB_ROOT_PASSWORD: chef
      MONGO_INITDB_DATABASE: master-chef
    volumes:
      - mongostore:/data/db

  # Web UI for mongo db
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: master
      ME_CONFIG_MONGODB_ADMINPASSWORD: chef


volumes:
  mongostore:
